language: node_js
node_js:
  - 12.22.12

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yml build --parallel
  - docker tag reverseproxy $DOCKER_USER/reverseproxy
  - docker tag udagram-api-user $DOCKER_USER/udagram-api-user
  - docker tag udagram-api-feed $DOCKER_USER/udagram-api-feed
  - docker tag udagram-frontend:local $DOCKER_USER/udagram-frontend

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $DOCKER_USER/reverseproxy
  - docker push $DOCKER_USER/udagram-api-user
  - docker push $DOCKER_USER/udagram-api-feed
  - docker push $DOCKER_USER/udagram-frontend

after_success:
  - echo "Success"
